AWSTemplateFormatVersion: '2010-09-09'
Description: VPC with public and private subnets and a NAT Gateway

Resources:
  FridayHittVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: FridayHittVPC

  FridayHittInternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: FridayHittInternetGateway

  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref FridayHittVPC
      InternetGatewayId: !Ref FridayHittInternetGateway

  PublicSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref FridayHittVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - 0
        - !GetAZs
            Ref: 'AWS::Region'
      Tags:
        - Key: Name
          Value: PublicSubnet

  ApplicationSubnet:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref FridayHittVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select
        - 1
        - !GetAZs
            Ref: 'AWS::Region'
      Tags:
        - Key: Name
          Value: ApplicationSubnet

  DatabaseSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref FridayHittVPC
      CidrBlock: 10.0.3.0/24
      AvailabilityZone: !Select 
        - 2
        - !GetAZs ''
      Tags:
        - Key: Name
          Value: DatabaseSubnet          

  NATGatewayEIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      Domain: vpc

  NATGateway:
    Type: 'AWS::EC2::NatGateway'
    Properties:
      AllocationId: !GetAtt NATGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnet
      Tags:
        - Key: Name
          Value: FridayHittNATGateway

  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref FridayHittVPC
      Tags:
        - Key: Name
          Value: PublicRouteTable

  DefaultPublicRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref FridayHittInternetGateway

  PublicSubnetRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  PrivateRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref FridayHittVPC
      Tags:
        - Key: Name
          Value: PrivateRouteTable

  DefaultPrivateRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref ApplicationSubnet
      RouteTableId: !Ref PrivateRouteTable

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref DatabaseSubnet
      RouteTableId: !Ref PrivateRouteTable    

Outputs:
  VPCId:
    Description: The ID of the VPC
    Value: !Ref FridayHittVPC
  PublicSubnetId:
    Description: The ID of the public subnet
    Value: !Ref PublicSubnet
  InternetGatewayId:
    Description: The ID of the Internet Gateway
    Value: !Ref FridayHittInternetGateway
  ApplicationSubnetId:
    Description: The ID of Private Subnet for Appilcation servers
    Value: !Ref ApplicationSubnet 
  DatabaseSubnetId:
    Description: The ID of the Private Subnet for Database servers
    Value: !Ref DatabaseSubnet   
